[build]
  publish = "dist"
  command = "npm run build"
  environment = { VUE_APP_NETLIFY = true }

[dev]
  publish = "dist"
  command = "npm run serve"
  port = 3000
  environment = { VUE_APP_NETLIFY = true }

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
